-- ============================================================================
-- 0004_orders.sql — Orders + order items + the atomic order/stock function
--                  (STEP 5, part A: database foundation only, no UI).
--
-- Extends the STEP 1 catalog (0001_init.sql), the STEP 2 galleries
-- (0002_product_images.sql) and the STEP 3 inventory (0003_variants.sql).
-- One client store per Supabase project; applied via the project's SQL editor
-- or `supabase db push` alongside 0001–0003 (which are never edited).
--
-- Model (deliberately narrow — no payments, no dashboards, no coupons):
--
--   orders ─┬─ order_items (order_id → orders.id, ON DELETE CASCADE)
--           │      product_id → products.id          (history is PROTECTED:
--           │      variant_id → variants.id           products/variants cannot
--           │                                         be deleted while ordered)
--           └─ money is stored as INTEGER TOMAN (bigint), never floats.
--
--   Two independent status axes, both stored as the PERSIAN customer-facing
--   label (the same strings the UI shows — no translation table to drift):
--     • payment_status — «در انتظار پرداخت» / «پرداخت شده» / «ناموفق» /
--                        «بازگشت وجه»
--     • order_status   — «در انتظار پرداخت» / «پردازش سفارش» / «آماده ارسال» /
--                        «ارسال شده» / «تحویل داده شده» / «لغو شده»
--   A brand-new order starts on «در انتظار پرداخت» for BOTH axes. Which
--   transitions are legal is business logic (a later step); only the DOMAIN is
--   enforced here, so a typo'd status can never be written.
--
-- THE POINT OF THIS MIGRATION — overselling must be impossible:
--   `public.create_order_with_items(...)` inserts the order + its items and
--   decrements `variants.stock_quantity` in ONE PostgreSQL transaction. Every
--   decrement is a guarded UPDATE
--       update variants set stock_quantity = stock_quantity - qty
--        where id = <variant> and stock_quantity >= qty;
--   and ZERO affected rows raises an exception, which rolls the WHOLE order
--   back — no order row, no partial stock change. Two customers racing for the
--   last unit therefore cannot both succeed: the second UPDATE re-reads the
--   committed value and finds `stock_quantity >= qty` false.
--   The function is also the ONLY writer of prices: it re-reads
--   `coalesce(products.discount_price, products.base_price)`, the product title
--   and the colour/size/SKU from the database, so a tampered client cannot
--   influence what an order costs. The client sends only
--   `{ product_id, variant_id, quantity }`.
--
-- NOTE on transactions: every plpgsql FUNCTION already runs inside the caller's
-- transaction, and PostgreSQL REJECTS transaction control (BEGIN/COMMIT) inside
-- a function body ("cannot commit while a PL/pgSQL function is running"). The
-- atomicity guarantee here is therefore the implicit single transaction plus the
-- RAISE that aborts it — which is strictly SAFER than committing halfway (a
-- COMMIT would make a later failure leave a half-finished order behind). Callers
-- that want an explicit block simply do:
--     begin;
--       select public.create_order_with_items(...);
--     commit;
--
-- Money shape: the existing price columns in 0001_init.sql are `numeric`;
-- order money is `bigint` (integer toman) so an order total can never carry a
-- fractional toman. The function casts once, at the point where it reads the
-- price.
--
-- NO explicit GRANTs here — 0001–0003 add none either, and PostgreSQL grants
-- EXECUTE on new functions to PUBLIC by default. The auth/RLS step tightens
-- this to the app role.
-- NOTE: Row Level Security and policies are intentionally NOT added here — they
-- arrive with the auth/roles step. Until then these tables remain accessible via
-- the anon key; do not expose them publicly (an order row is personal data).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- orders — one row per checkout submission (header + money + the two statuses)
-- ----------------------------------------------------------------------------
create table public.orders (
  id               uuid primary key default gen_random_uuid(),
  -- Customer-facing, human-readable reference (generated by the app:
  -- e.g. ORD-20260927-0001). UNIQUE = a duplicate submission can never create a
  -- second row with the same reference.
  order_number     text not null unique,
  customer_name    text not null,
  customer_phone   text not null,
  customer_email   text,                                   -- optional
  shipping_address text not null,
  notes            text,                                   -- optional, customer note
  -- Integer Toman. Both amounts are computed by the DB function from the live
  -- catalog — never sent by the client. No shipping/taxes in this step, so
  -- total_amount equals subtotal_amount (kept separate so shipping can be added
  -- without a migration of the shape).
  subtotal_amount  bigint not null default 0 check (subtotal_amount >= 0),
  total_amount     bigint not null default 0 check (total_amount >= 0),
  payment_status   text not null default 'در انتظار پرداخت' check (payment_status in (
    'در انتظار پرداخت', 'پرداخت شده', 'ناموفق', 'بازگشت وجه'
  )),
  order_status     text not null default 'در انتظار پرداخت' check (order_status in (
    'در انتظار پرداخت', 'پردازش سفارش', 'آماده ارسال', 'ارسال شده', 'تحویل داده شده', 'لغو شده'
  )),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  -- An order with a blank reference / name / phone / address is unfulfillable
  -- and unsearchable — reject it at the DB (same style as 0003's blank checks).
  constraint orders_order_number_not_blank check (btrim(order_number) <> ''),
  constraint orders_customer_name_not_blank check (btrim(customer_name) <> ''),
  constraint orders_customer_phone_not_blank check (btrim(customer_phone) <> ''),
  constraint orders_shipping_address_not_blank check (btrim(shipping_address) <> '')
);

comment on table public.orders is
  'One row per checkout submission (STEP 5). Money is integer Toman (bigint); both statuses store the exact Persian label the customer sees. Written only through public.create_order_with_items(), which prices the order from the live catalog inside one transaction.';
comment on column public.orders.order_number is
  'Human-readable public reference (e.g. ORD-20260927-0001, generated by the app in src/lib/orders.ts). UNIQUE: the same reference can never produce two orders.';
comment on column public.orders.customer_email is
  'Optional. Null when the customer did not provide an email.';
comment on column public.orders.notes is
  'Optional free-text note from the customer (delivery instructions etc.).';
comment on column public.orders.subtotal_amount is
  'Sum of order_items.line_total, in integer Toman. Computed by public.create_order_with_items() from variant prices — never accepted from the client.';
comment on column public.orders.total_amount is
  'Amount payable, integer Toman. Equals subtotal_amount in this step (shipping/taxes are out of scope); kept separate so they can be added later.';
comment on column public.orders.payment_status is
  'Payment axis: در انتظار پرداخت | پرداخت شده | ناموفق | بازگشت وجه. Starts at «در انتظار پرداخت»; gateways (later step) move it.';
comment on column public.orders.order_status is
  'Fulfilment axis: در انتظار پرداخت | پردازش سفارش | آماده ارسال | ارسال شده | تحویل داده شده | لغو شده. Starts at «در انتظار پرداخت»; admin UI (later step) moves it.';
comment on column public.orders.updated_at is
  'Maintained by the shared public.set_updated_at() trigger function created in 0001_init.sql.';

-- Admin/staff list (newest first) once an orders screen exists.
create index orders_created_at_idx on public.orders (created_at desc);

-- ----------------------------------------------------------------------------
-- order_items — the frozen lines of an order (snapshot, never a live join)
-- ----------------------------------------------------------------------------
create table public.order_items (
  id                     uuid primary key default gen_random_uuid(),
  order_id               uuid not null references public.orders (id) on delete cascade,
  -- Catalog references are PROTECTED (default NO ACTION): a product or variant
  -- that has been ordered cannot be deleted while the order exists. Retailers
  -- retire catalog rows with products.status / variants.status instead of
  -- deleting them (the deferred admin step). Deleting a CATEGORY cascades to its
  -- products, so it will also be refused while any of those products is ordered
  -- — that is the intended, safe behaviour: order history is never silently lost.
  product_id             uuid not null references public.products (id),
  variant_id             uuid not null references public.variants (id),
  -- Snapshot of what the customer actually bought. The catalog may be renamed,
  -- repriced or retired afterwards; an order must keep reading the same.
  product_title_snapshot text not null,
  variant_snapshot       jsonb not null,   -- { "color": …, "size": …, "sku": … }
  -- Money + quantity as ordered (integer Toman); recomputed by the DB function.
  unit_price             bigint not null check (unit_price >= 0),
  quantity               integer not null check (quantity > 0),
  line_total             bigint not null check (line_total >= 0),
  -- One line per variant per order, with the quantity summed (the cart already
  -- aggregates, and the DB refuses to store the same variant twice in one order).
  constraint order_items_order_id_variant_id_key unique (order_id, variant_id)
);

comment on table public.order_items is
  'Frozen order lines (STEP 5). Each row snapshots the product title and the colour/size/SKU so an order stays readable even after the catalog changes; prices are integer Toman computed by public.create_order_with_items().';
comment on column public.order_items.order_id is
  'Owning order; lines are removed automatically when the order is deleted (on delete cascade).';
comment on column public.order_items.product_id is
  'Ordered product. NO ACTION: the product cannot be deleted while it appears in any order (retire it with status instead).';
comment on column public.order_items.variant_id is
  'Ordered colour/size variant. NO ACTION: same protection as product_id. This is the row whose stock_quantity the order function decrements.';
comment on column public.order_items.variant_snapshot is
  'jsonb snapshot frozen at purchase time: { "color", "size", "sku" } as they were ordered — never re-read from public.variants.';
comment on column public.order_items.unit_price is
  'Price of ONE unit at purchase time, in integer Toman: coalesce(products.discount_price, products.base_price) as read inside the transaction.';
comment on column public.order_items.line_total is
  'unit_price × quantity, in integer Toman.';

-- Order + its lines is the single lookup every order screen performs.
create index order_items_order_id_idx on public.order_items (order_id);

-- updated_at maintenance — reuses the SHARED trigger function defined once in
-- 0001_init.sql (public.set_updated_at); no second function is created here.
-- order_items has no timestamps: a line is immutable once written (see 0003's
-- note about never redefining the shared function).
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- create_order_with_items — the ONLY write path that creates an order.
--
--   • one transaction: order row + lines + stock decrements all commit together
--     or not at all (see the header note about BEGIN/COMMIT in plpgsql);
--   • client input is limited to ids and quantities (`p_items`):
--         [ { "product_id": "<uuid>", "variant_id": "<uuid>", "quantity": 2 }, … ]
--     title / colour / size / SKU / unit price are read from the catalog HERE,
--     so prices can never be spoofed by the caller;
--   • every failure raises with a Persian message (the same wording the cart
--     uses) plus a machine-readable `hint` (reason code) so the app can map it:
--         empty-cart | invalid-input | duplicate-variant | product-missing |
--         variant-missing | inactive | invalid-quantity | insufficient-stock |
--         order-number-taken
--   • `stock_quantity = stock_quantity - qty … and stock_quantity >= qty`
--     is the overselling guard: 0 rows updated ⇒ RAISE ⇒ full rollback.
--
-- security definer + a pinned search_path: the function must keep working after
-- RLS arrives (it is the sanctioned way for a customer to write orders and
-- decrement stock) and cannot be hijacked through a caller-controlled
-- search_path.
-- ----------------------------------------------------------------------------
create or replace function public.create_order_with_items(
  p_order_number     text,
  p_customer_name    text,
  p_customer_phone   text,
  p_customer_email   text,
  p_shipping_address text,
  p_notes            text,
  p_items            jsonb
)
returns public.orders
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order          public.orders;
  v_item           jsonb;
  v_product_id     uuid;
  v_variant_id     uuid;
  v_quantity       integer;
  v_price          bigint;
  v_title          text;
  v_product_status text;
  v_variant        public.variants;
  v_subtotal       bigint := 0;
  v_updated        integer;
  v_seen           uuid[] := '{}';
begin
  -- ── 1) Shape of the request ────────────────────────────────────────────────
  if btrim(coalesce(p_order_number, '')) = ''
     or btrim(coalesce(p_customer_name, '')) = ''
     or btrim(coalesce(p_customer_phone, '')) = ''
     or btrim(coalesce(p_shipping_address, '')) = '' then
    raise exception 'اطلاعات سفارش کامل نیست'
      using errcode = 'P0001', hint = 'invalid-input';
  end if;

  if p_items is null
     or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 then
    raise exception 'سبد خرید شما خالی است'
      using errcode = 'P0001', hint = 'empty-cart';
  end if;

  -- ── 2) Order header first — amounts are filled in at the end, once every
  --      line has been priced and reserved. A raised error discards this row. ──
  insert into public.orders (
    order_number, customer_name, customer_phone, customer_email,
    shipping_address, notes, subtotal_amount, total_amount,
    payment_status, order_status
  )
  values (
    btrim(p_order_number),
    btrim(p_customer_name),
    btrim(p_customer_phone),
    nullif(btrim(coalesce(p_customer_email, '')), ''),
    btrim(p_shipping_address),
    nullif(btrim(coalesce(p_notes, '')), ''),
    0, 0,
    'در انتظار پرداخت', 'در انتظار پرداخت'
  )
  returning * into v_order;

  -- ── 3) Price + reserve every line from the DATABASE ────────────────────────
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_product_id := (v_item ->> 'product_id')::uuid;
    v_variant_id := (v_item ->> 'variant_id')::uuid;
    v_quantity   := (v_item ->> 'quantity')::integer;

    if v_quantity is null or v_quantity <= 0 then
      raise exception 'موجودی کافی نیست'
        using errcode = 'P0001', hint = 'invalid-quantity';
    end if;

    -- Same variant twice → the unique (order_id, variant_id) index would fail
    -- anyway; fail early with an explicit reason.
    if v_variant_id = any (v_seen) then
      raise exception 'سفارش تکراری'
        using errcode = 'P0001', hint = 'duplicate-variant';
    end if;
    v_seen := v_seen || v_variant_id;

    -- Product must exist and be sellable.
    select p.status, p.title, (coalesce(p.discount_price, p.base_price))::bigint
      into v_product_status, v_title, v_price
      from public.products p
     where p.id = v_product_id;
    if not found then
      raise exception 'این محصول موجود نیست'
        using errcode = 'P0001', hint = 'product-missing';
    end if;
    if v_product_status <> 'active' then
      raise exception 'این محصول موجود نیست'
        using errcode = 'P0001', hint = 'inactive';
    end if;

    -- Variant must belong to that product and be sellable. (Cart-level wording:
    -- an unknown/retired variant can no longer be bought — «این محصول موجود
    -- نیست» is the honest message, exactly like the cart's `inactive` case.)
    select * into v_variant
      from public.variants v
     where v.id = v_variant_id
       and v.product_id = v_product_id;
    if not found then
      raise exception 'این محصول موجود نیست'
        using errcode = 'P0001', hint = 'variant-missing';
    end if;
    if v_variant.status <> 'active' then
      raise exception 'این محصول موجود نیست'
        using errcode = 'P0001', hint = 'inactive';
    end if;

    -- THE overselling guard. Guarded update: it only fires when enough stock is
    -- actually on hand, and takes a row lock, so concurrent orders serialise.
    update public.variants
       set stock_quantity = stock_quantity - v_quantity
     where id = v_variant_id
       and stock_quantity >= v_quantity;
    get diagnostics v_updated = row_count;
    if v_updated = 0 then
      raise exception 'موجودی کافی نیست'
        using errcode = 'P0001', hint = 'insufficient-stock';
    end if;

    insert into public.order_items (
      order_id, product_id, variant_id,
      product_title_snapshot, variant_snapshot,
      unit_price, quantity, line_total
    )
    values (
      v_order.id, v_product_id, v_variant_id,
      v_title,
      jsonb_build_object('color', v_variant.color, 'size', v_variant.size, 'sku', v_variant.sku),
      v_price, v_quantity, v_price * v_quantity
    );

    v_subtotal := v_subtotal + (v_price * v_quantity);
  end loop;

  -- ── 4) Totals, computed from the lines just written (no shipping/taxes). ───
  update public.orders
     set subtotal_amount = v_subtotal,
         total_amount    = v_subtotal
   where id = v_order.id
  returning * into v_order;

  return v_order;
end;
$$;

comment on function public.create_order_with_items(text, text, text, text, text, text, jsonb) is
  'Atomic order creation (STEP 5): inserts the order + lines and decrements variants.stock_quantity in one transaction, pricing everything from the catalog. Raises (rolling back) with a Persian message + hint when a product/variant is missing or inactive, or stock is insufficient — overselling is impossible. Example: select public.create_order_with_items(''ORD-20260927-0001'', ''نام'', ''09120000000'', null, ''نشانی'', null, ''[{"product_id":"…","variant_id":"…","quantity":2}]''::jsonb);';

-- ----------------------------------------------------------------------------
-- LATER (not this step):
--   • checkout UI, payment gateway callback → payment_status / order_status
--   • customer auth + "my orders" (orders would gain customer_id)
--   • admin/staff orders screen (status transitions, fulfilment, refunds)
--   • RLS enable + policies (customers read only their own order); grants for
--     the app role limit EXECUTE of create_order_with_items to that role
--   • a submission-token column + unique index for idempotent retries (today the
--     guard lives in src/lib/orders.ts; the column set here is intentionally
--     fixed to the STEP 5 brief)
-- ============================================================================
